### ISSUE TITLE
-LRB- and -RRB- in Form and Lemma

### ISSUE THREAD

**Issue by foxik** [UniversalDependencies/UD_English#1]
The -LRB- and -RRB- are currently used instead of "(" and ")" in Form, and -lrb- and -rrb- instead of "(" and ")" in Lemma. I think plain "(" and ")" shoulud be used. In UD 1.1, English is the only language which does not use plain "(" and ")" in forms.

I understand that -LRB- and -RRB- (and in past -LCB-, -RCB-, -LSB-, -RSB-) are used in Penn Treebank formats, because "(" and ")" have special meaning in that format. But since "(" and ")" are not special in CoNLL-U, I believe using "(" and ")" instead of -LRB- and -RRB- would be better.

**Comment by foxik** [comment]
I am happy to create a pull request with this change, if you agree.

**Comment by jnivre** [comment]
This has been discussed before, although I don't remember whether it was ever formally raised as an issue. Personally, I am all in favor of getting rid of the old -LRB- and -RRB- in the interest of uniformity across languages, but I remember that the English were a little reluctant because most (?) English tokenizers actually output -LRB- and -RRB- rather than ( and ). Perhaps it is time to settle this once and for all.

**Comment by fginter** [comment]
I think this is the 3rd time this issue is raised. If this should be once and for all, then I cannot miss the opportunity to say :+1: for getting rid of those.

**Comment by dan-zeman** [comment]
The previous issue about this was opened at the docs repository, here: https://github.com/UniversalDependencies/docs/issues/148

There seems to be consensus that the escaping should be dropped, it just has not happened yet. Perhaps the only question here is whether the UD_English team are prepared to receive the update via a pull request. If they have done other changes in the meantime, which have not been pushed, it may be difficult to merge. @manning @ngiordani @tdozat could you please comment on this.

**Comment by foxik** [comment]
To move things forward, I created a pull request. I am happy to rebase it at any time, so if/when we are ready to merge it, I will update it.

**Comment by sebschu** [comment]
Thanks for the pull request, @foxik, but we are actually not directly editing the files that we are pushing to the public GitHub repository, so this would get overwritten again with the next release. We'll discuss this in our meeting on Friday but I think we should be able to make this change for the next release.

**Comment by foxik** [comment]
@sebschu Thanks for clarifying, I will close the pull request.

**Comment by manning** [comment]
Agreed.  We will change this to use ( and ).  I think we can do this for the version 1.2 release.
Thanks for offering pull requests @foxik, but I think in practice that since we annotate article-specific files and then concatenate to produce the released UD files, that it would be easier for us to just do this ourselves....

**Comment by foxik** [comment]
I understand. This is a trivial change, so performing it by yourselves would be probably easier even if you used this repository as a primary source.

Thanks for doing this in the 1.2 release.

**Comment by manning** [comment]
Notwithstanding that there are still validation errors to be addressed, this is fixed in our version 1.2 release candidate.
