### ISSUE TITLE
English != US English

### ISSUE THREAD

**Issue by MarcusJT** [UniversalDependencies/UD_English#10]
To most people in the world, when used unqualified "English" means English from England (i.e. UK English) not US English, but on http://universaldependencies.org/ this remains unclear and displayed only with an American flag.

If there are zero differences between UK English and US English as far as UD is concerned then it should clarify this (and use a UK flag), else surely there should be separate English UK (en-gb) and English US (en-us) treebanks with appropriate flags?

**Comment by fginter** [comment]
This flag has been decided in the following email discussion, initiatied by the UD_English contributors.

```
Dan Zeman zeman@ufal.mff.cuni.cz via utu.fi 
11/1/15

to Filip, Natalia, Joakim 
US flag is OK, I actually did the same on the HamleDT page.

Note however that the UD_Portuguese data is *not* the Brazilian Portuguese treebank from Google. Reportedly it is a mixture of Portugal and Brazil, that's why I went for the flag of Portugal.

Dan

From: "Filip Ginter" <figint@utu.fi>
To: "Natalia Silveira" <natalias@stanford.edu>
Cc: "Daniel Zeman" <zeman@ufal.mff.cuni.cz>, "Joakim Nivre" <joakim.nivre@lingfil.uu.se>
Sent: Sunday, November 1, 2015 10:12:38 AM
Subject: Re: flags on main page


Done. I'm totally fine with that. :) I just got that flag list from
upstream and never took any position on which flag goes where, just
being the code monkey here. :)

cc: Dan, Joakim FYI

Cheers,

F

PS: One just needs to edit flags.json in gen_index and wait for the
system to pick the change up


On Sun, Nov 1, 2015 at 10:56 AM, Natalia Silveira <natalias@stanford.edu> wrote:
> Hi Filip,
>
> thanks for putting up the great-looking new main page! I was wondering if it
> would be possible to change the UK flag to a US flag, since the corpus is in
> American English. (And I guess by the same argument I would suggest using
> Brazil's flag instead of Portugal's. :)) I'd be happy to do it, just not
> sure where the files live.
>
> Thanks!
> Natalia
```

**Comment by dan-zeman** [comment]
Unfortunately, at present we do not seem to have any dataset with UK English. When such a dataset is added, we will surely use the UK flag next to it.

**Comment by MarcusJT** [comment]
So it IS American English, which is fine, but then the only indicator of this is the flag, which isn't really sufficient (especially not from an accessibility perspective) - it should be named/labelled "American English" or "English (US)" as well

**Comment by dan-zeman** [comment]
We more or less follow the granularity of the ISO 639 language codes. Finer distinctions, such as dialect, time period, type of text / genre etc. can (or at least should be) described in the documentation.

**Comment by ftyers** [comment]
I agree, the way around this would be to either convert the US data to European English (UK, Ireland, Malta) and offer a separate download. It shouldn't be too hard to do, although would require manual checking for some of the morpho-syntactic stuff. I'd be happy to participate.

**Comment by jnivre** [comment]
I think there are two separate issues here, each with its own complexities. 

The first is the use of flags to represent languages, which is clearly never going to be exact. What is the appropriate flag for Gothic, for example, a language that was extinct before (national) flags existed and is not associated with any particular country? We had lots of discussion before putting flags on the web page, but in the end we decided to do it because people like it. Flags add color and are easy to recognize, but they always have to be taken with a pinch of salt. So the best we can do is to put a warning about this on the page.

The second issue is about language classification, which again is never going to be exact. There are simply no linguistic criteria that allow us to decide what are distinct languages, as opposed to dialects of a single language. Hence, the old linguist joke that a language is a dialect with an army and a navy. More importantly, even if most of the data in the English UD treebank can be classified as American English, we can never be totally sure that all of it is, given the way the data was collected. There could be other varieties of English, including (quite probably) English produced by non-native speakers (like me) who will happily mix different varieties as well as make grammatical mistakes. So the most specific claim we can make about it is that it is English. The idea of converting the data from one standard to another is interesting (and potentially useful), but I wouldn't treat the result as a UD treebank. This data is intended (primarily) for scientific research, so we can't tamper with the data.

**Comment by MarcusJT** [comment]
Thanks @jnivre, that's very interesting indeed. Sounds like it's far more complicated than I thought and that it's best to leave things the way they are.
