### ISSUE TITLE
possessive determiners: inconsistency between doc & corpus

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_English#14]
On doc page for determiners (http://universaldependencies.org/u/pos/DET.html), in  Examples section, there are: 
- possessive determiners: _my_, _your_, _his_, _her_, _its_, _our_, _their_

But in the corpus, these forms have always the PRON POS:
http://talc2.loria.fr/grew/?custom=581320b57a11d&corpus=UD_English-1.3

What is the correct POS in these cases: DET or PRON?

**Comment by jnivre** [comment]
Under v1 of the guidelines, it should be DET, so this has to be considered a bug in the English treebank. But it is currently under discussion for v2, so for the moment it is best to suspend judgement.

**Comment by manning** [comment]
My understanding of v2 is that we can leave them as PRON, and I really feel this is the best choice for most languages (because it makes pronominal and nominal possessors parallel in structure). So my plan is to do nothing here. Right?

**Comment by nschneid** [comment]
The [v2 update](http://universaldependencies.org/v2/postags.html) says: 

> Possessives vary across languages. In some languages the above tests put them in the `DET` category. In others, they are more like a normal personal pronoun in a specific case (often the genitive), or a personal pronoun with an adposition; they are tagged `PRON`.

From this I take it that the decision is to be on a per-language basis. However, the [`DET`](http://universaldependencies.org/u/pos/DET.html) documentation lists the possessive determiners as a subtype. So it seems the documentation is inconsistent.

**Comment by dan-zeman** [comment]
@manning : yes you can leave them as `PRON`. I don't have statistics in how many languages this would be the best choice but I agree that in English the evidence for the opposite is not particularly strong.

@nschneid : thanks for pointing this out. The documentation was still somewhat v1-oriented but I tried to fix it now. (Examples of possessive determiners are now taken from Czech instead of English to avoid confusion. But I also extended the text by stuff that we had in the v2 proposal and forgot to propagate it here.)
