### ISSUE TITLE
"nsubj" in existential clauses

### ISSUE THREAD

**Issue by interrogator** [UniversalDependencies/UD_English#9]
I'm having trouble with what I see as an inconsistency in the definition and application of the `nsubj` label. It is explicitly defined [here](http://universaldependencies.org/docs/u/dep/all.html):

    "A nominal subject is a nominal phrase which is the syntactic subject of a clause".

In existential clauses, however, the existent is also labelled as `nsubj`, as in the example:

    There is a ghost in the room
    nsubj(is, ghost)

Surely `There` is the (albeit dummy) syntactic subject in an existential construction. `ghost` certainly doesn't fit the `nsubj` definition. Is the label definition up-to-date and justifiable?

I suppose the problem is that `ghost` doesn't fit the definition for `dobj` either:

    "The direct object of a verb is the noun phrase that denotes the entity acted upon".

This is perhaps a bigger problem though, where some label definitions are syntactic, some semantic, and some a mixture of both.

**Comment by ftyers** [comment]
At least from the subject-verb agreement, subject seems to be right here:

    There are ghosts in the room.
    There is a ghost in the room.

The "there" is `expl`,

**Comment by interrogator** [comment]
Subject-verb agreement isn't really useful here, especially since informal usage often turns up the opposite:

    There's people everywhere!

Better is the use of an interrogative tag, which takes the grammatical subject as pronoun and finite w/ polarity reversed:

    There are ghosts in the room, aren't there?
    *There are ghosts in the room, aren't they?
    There's ghosts in the room, isn't there?

`There` is said to be the grammatical subject in Quirk et al, Huddleston & Pullum, Halliday & Matthiessen, etc. I've not seen any reputable published sources claiming otherwise. If anyone has encountered one, please do let me know!

**Comment by jnivre** [comment]
Thanks for drawing our attention to these shortcomings. We clearly need to improve on our definitions for the next release of the guidelines (possibly sooner than that if it can be seen as simple bug fixes).

As for existential "there" and similar constructions, I agree that "there" passes the test for being the grammatical subject (as does the pleonastic "it" in "it rains"). At the same time, it is clear that "a ghost" is not a direct object. It cannot be promoted to subject by passivising, for example. Many grammarians would say that these sentences has a formal subject ("there") as well as a logical subject ("a ghost"). Our current policy is to use "expl" for formal subject and "nsubj" for logical subjects in such cases. But this definitely needs to be clarified in the documentation.

**Comment by interrogator** [comment]
Thanks for this clarification. Yes, I'd really love if the project committed to a more rigorous set of relationship definitions, that may be either semantic or syntactic, but preferably not both, as I think that can only lead to confusion.

This distinction between types of subjecthood is obviously ideal, but I'm sure it's tough to implement without either joining role tags together or having multiple layers of annotation. My guess is that almost all work done with dependency parsing is centred on extracting experiential/logical meanings, rather than grammatical/mood ones. It could therefore make sense to try to isolate the features of the transitivity system as the label set, while isolating syntax as the linguistic stratum that informs definitions, etc.

Thanks for all the awesome work, by the way!

**Comment by manning** [comment]
A few belated remarks from me:

- I of course agree that there are some awkward compromises here. Existential constructions are a well-known tricky topic on which much ink has been spilt, and we have indeed revised our own account several times.
- I agree that the expletive passes typical tests for being grammatical subject.
- However, it is then very unclear what to call *a ghost* and you see awkward invented relations. For instance Huddleston and Pullum go with "displaced subject".  (Is a "displaced" subject not a subject?)
- It's easy to say that one should not mix syntactic and semantic definitions, but in practice, I think grammarians normally do, and in particular, if you have a monostratal theory like the current UD, then I think it is almost inevitable.
- Everything is open to revision, but our current decision has been to use nsubj/dobj only for semantic arguments, and to use a different label (`expl`) for expletive arguments. 
- Since the `expl` role is given to the expletive subject, it seemed convenient to use nsubj as the relation for the "displaced subject" (!).
- This choice seems at least somewhat useful for typical relation extraction type applications and for parallelism with other languages that lack expletives but have existential verbs (e.g., Japanese heya ni yuurei ga iru  room LOC ghost NOM be).

I'm going to close this as this isn't at present an error to be fixed, but we welcome involvement on possibilities for improving UD for v2.
